### ISSUE TITLE
Create cell by mentioning level

### ISSUE THREAD

**Issue by sivalearn12** [google/s2-geometry-library-java#13]
Hi,
i want to create the cell by mentioning the level.

S2Cell cell = new S2Cell(S2LatLng.fromDegrees(0.5, 14.3).toPoint());

S2CellId cellid = cell.id();

cellid.level() // its coming as 30.. is it possible to change the level to 12.

**Comment by eengle** [comment]
'cellid.parent(12)' should do the trick.
