### ISSUE TITLE
Java port for S2RegionTermIndexer (c++)

### ISSUE THREAD

**Issue by nomad10101** [google/s2-geometry-library-java#32]
I am trying to port a c++ application to Java that uses S2RegionTermIndexer class in s2-geometry c++ library. I do not see a corresponding Java implementation for this class in this repo.

In short, I am specifically trying to address the use-case addressed in section titled  "Indexing for Search " & "Querying for Search" in s2-geometry quickstart here: https://s2geometry.io/devguide/cpp/quickstart.

My questions are:
- Is there a Java implementation for S2RegionTermIndexer or equivalent functionality
- Is this on the roadmap/backlog
- The c++ implementation for S2RegionTermIndexer class is under 300 loc. This looks like a fairly straight forward translation effort. Is there anything I need to know (i.e. pitfalls etc) if I try to port the c++ logic to java for my project.

Any feedback is appreciated.

**Comment by alleyZ** [comment]
+1

**Comment by dmitryzv** [comment]
+1
