### ISSUE TITLE
S1Angle.fromEarthDistance

### ISSUE THREAD

**Issue by Myjacklee** [google/s2-geometry-library-java#37]
Where is the method S1Angle.fromEarthDistance() , the S1Angle.fromEarthDistance(5000) is mentioned in class S2ClosestPointQuery , but I can't find it

**Comment by jmr** [comment]
`S1Angle.fromEarthDistance` is deprecated and was never released. The right way would be with `S2Earth`, but that hasn't been released yet either. You can use `... EARTH_RADIUS_KM = 6371.01; S1Angle.fromRadians(5 /  EARTH_RADIUS_KM)`.
